//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobList.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobList.Resources.ConfigResources", typeof(ConfigResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADM.
        /// </summary>
        public static string AdminAudience {
            get {
                return ResourceManager.GetString("AdminAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultConnection.
        /// </summary>
        public static string DefaultConnection {
            get {
                return ResourceManager.GetString("DefaultConnection", resourceCulture);
            }
        }
        
        /// <summary>

        ///   Looks up a localized string similar to UTPEgresados.
        /// </summary>
        public static string EgresadoAudience {
            get {
                return ResourceManager.GetString("EgresadoAudience", resourceCulture);
                }
        }
        ///   Looks up a localized string similar to DCT.
        /// </summary>
        public static string DocenteAudience {
            get {
                return ResourceManager.GetString("DocenteAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMP.
        /// </summary>
        public static string EmpresaAudience {
            get {
                return ResourceManager.GetString("EmpresaAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginServiceUTP2023.
        /// </summary>
        public static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string RolAdmin {
            get {
                return ResourceManager.GetString("RolAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egresado.
        /// </summary>
        public static string RolEgresado {
            get {
                return ResourceManager.GetString("RolEgresado", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Docente.
        /// </summary>
        public static string RolDocente {
            get {
                return ResourceManager.GetString("RolDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string RolEmpresa {
            get {
                return ResourceManager.GetString("RolEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondaryConnection.
        /// </summary>
        public static string SecondaryConnection {
            get {
                return ResourceManager.GetString("SecondaryConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings.
        /// </summary>
        public static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
    }
}
