//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobList.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoredProcedureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobList.Resources.StoredProcedureResources", typeof(StoredProcedureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idEmpresa.
        /// </summary>
        public static string _idEmpresa {
            get {
                return ResourceManager.GetString("_idEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _accionestadopostulacion.
        /// </summary>
        public static string AccionEstadoPostulacion {
            get {
                return ResourceManager.GetString("AccionEstadoPostulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _actividadEmpresa.
        /// </summary>
        public static string ActividadEmpresa {
            get {
                return ResourceManager.GetString("ActividadEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _actividadPrincipal.
        /// </summary>
        public static string ActividadPrincipal {
            get {
                return ResourceManager.GetString("ActividadPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _cargo.
        /// </summary>
        public static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ConocimientoID.
        /// </summary>
        public static string ConocimientoID {
            get {
                return ResourceManager.GetString("ConocimientoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _correo.
        /// </summary>
        public static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _correoEmpresa.
        /// </summary>
        public static string CorreoEmpresa {
            get {
                return ResourceManager.GetString("CorreoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _correoResponsable.
        /// </summary>
        public static string CorreoResponsable {
            get {
                return ResourceManager.GetString("CorreoResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CP.
        /// </summary>
        public static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _descripcion.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _descripcionEgresado.
        /// </summary>
        public static string DescripcionEgresado {
            get {
                return ResourceManager.GetString("DescripcionEgresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _descripcionEmpresa.
        /// </summary>
        public static string DescripcionEmpresa {
            get {
                return ResourceManager.GetString("DescripcionEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _descripcionPuesto.
        /// </summary>
        public static string DescripcionPuesto {
            get {
                return ResourceManager.GetString("DescripcionPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _domicilio.
        /// </summary>
        public static string Domicilio {
            get {
                return ResourceManager.GetString("Domicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _domicilioFiscal.
        /// </summary>
        public static string DomicilioFiscal {
            get {
                return ResourceManager.GetString("DomicilioFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _edad.
        /// </summary>
        public static string Edad {
            get {
                return ResourceManager.GetString("Edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _empresa.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _mismaPassword.
        /// </summary>
        public static string EqualPassword {
            get {
                return ResourceManager.GetString("EqualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _fechaCaducidad.
        /// </summary>
        public static string FechaCaducidad {
            get {
                return ResourceManager.GetString("FechaCaducidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _fechaCreacion.
        /// </summary>
        public static string FechaCreacion {
            get {
                return ResourceManager.GetString("FechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _fechaPublicacion.
        /// </summary>
        public static string FechaPublicacion {
            get {
                return ResourceManager.GetString("FechaPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _generacion.
        /// </summary>
        public static string Generacion {
            get {
                return ResourceManager.GetString("Generacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _giro.
        /// </summary>
        public static string Giro {
            get {
                return ResourceManager.GetString("Giro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _horarioTrabajo.
        /// </summary>
        public static string HorarioTrabajo {
            get {
                return ResourceManager.GetString("HorarioTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idArea.
        /// </summary>
        public static string idArea {
            get {
                return ResourceManager.GetString("idArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idConocimiento.
        /// </summary>
        public static string idConocimiento {
            get {
                return ResourceManager.GetString("idConocimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idDatoContacto.
        /// </summary>
        public static string idDatoContacto {
            get {
                return ResourceManager.GetString("idDatoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idDetalleContacto.
        /// </summary>
        public static string idDetalleContacto {
            get {
                return ResourceManager.GetString("idDetalleContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idDivision.
        /// </summary>
        public static string idDivision {
            get {
                return ResourceManager.GetString("idDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idEmpresa.
        /// </summary>
        public static string idEmpresa {
            get {
                return ResourceManager.GetString("idEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idExperiencia.
        /// </summary>
        public static string idExperiencia {
            get {
                return ResourceManager.GetString("idExperiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idGenero.
        /// </summary>
        public static string idGenero {
            get {
                return ResourceManager.GetString("idGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idHabilidad.
        /// </summary>
        public static string idHabilidad {
            get {
                return ResourceManager.GetString("idHabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaArea.
        /// </summary>
        public static string idNuevaArea {
            get {
                return ResourceManager.GetString("idNuevaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaDivision.
        /// </summary>
        public static string idNuevaDivision {
            get {
                return ResourceManager.GetString("idNuevaDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaExperiencia.
        /// </summary>
        public static string idNuevaExperiencia {
            get {
                return ResourceManager.GetString("idNuevaExperiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaHabilidad.
        /// </summary>
        public static string idNuevaHabilidad {
            get {
                return ResourceManager.GetString("idNuevaHabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaOferta.
        /// </summary>
        public static string idNuevaOferta {
            get {
                return ResourceManager.GetString("idNuevaOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaResponsabilidad.
        /// </summary>
        public static string idNuevaResponsabilidad {
            get {
                return ResourceManager.GetString("idNuevaResponsabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoAdministrador.
        /// </summary>
        public static string idNuevoAdministrador {
            get {
                return ResourceManager.GetString("idNuevoAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoBeneficio.
        /// </summary>
        public static string idNuevoBeneficio {
            get {
                return ResourceManager.GetString("idNuevoBeneficio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoConocimiento.
        /// </summary>
        public static string idNuevoConocimiento {
            get {
                return ResourceManager.GetString("idNuevoConocimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoDocente.
        /// </summary>
        public static string idNuevoDocente {
            get {
                return ResourceManager.GetString("idNuevoDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoEgresado.
        /// </summary>
        public static string idNuevoEgresado {
            get {
                return ResourceManager.GetString("idNuevoEgresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoEstadoOferta.
        /// </summary>
        public static string idNuevoEstadoOferta {
            get {
                return ResourceManager.GetString("idNuevoEstadoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoEstadoPostulacion.
        /// </summary>
        public static string idNuevoEstadoPostulacion {
            get {
                return ResourceManager.GetString("idNuevoEstadoPostulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoUsuario.
        /// </summary>
        public static string idNuevoUsuario {
            get {
                return ResourceManager.GetString("idNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idOferta.
        /// </summary>
        public static string idOferta {
            get {
                return ResourceManager.GetString("idOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idPostulacion.
        /// </summary>
        public static string idPostulacion {
            get {
                return ResourceManager.GetString("idPostulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idTipo.
        /// </summary>
        public static string idTipo {
            get {
                return ResourceManager.GetString("idTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idTipoBuscado.
        /// </summary>
        public static string idTipoBuscado {
            get {
                return ResourceManager.GetString("idTipoBuscado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idUsuario.
        /// </summary>
        public static string idUsuario {
            get {
                return ResourceManager.GetString("idUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idUsuarioDocente.
        /// </summary>
        public static string idUsuarioDocente {
            get {
                return ResourceManager.GetString("idUsuarioDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idUsuarioEgresado.
        /// </summary>
        public static string idUsuarioEgresado {
            get {
                return ResourceManager.GetString("idUsuarioEgresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idUsuarioEmpresa.
        /// </summary>
        public static string idUsuarioEmpresa {
            get {
                return ResourceManager.GetString("idUsuarioEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _imgUrl.
        /// </summary>
        public static string ImgUrl {
            get {
                return ResourceManager.GetString("ImgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _lugar.
        /// </summary>
        public static string Lugar {
            get {
                return ResourceManager.GetString("Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _modalidad.
        /// </summary>
        public static string Modalidad {
            get {
                return ResourceManager.GetString("Modalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _nombreEmpresa.
        /// </summary>
        public static string NombreEmpresa {
            get {
                return ResourceManager.GetString("NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _nombreResponsable.
        /// </summary>
        public static string NombreResponsable {
            get {
                return ResourceManager.GetString("NombreResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _nuevaDescripcion.
        /// </summary>
        public static string NuevaDescripcion {
            get {
                return ResourceManager.GetString("NuevaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptada.
        /// </summary>
        public static string OfertaAceptada {
            get {
                return ResourceManager.GetString("OfertaAceptada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _opcion.
        /// </summary>
        public static string Opcion {
            get {
                return ResourceManager.GetString("Opcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _periodo.
        /// </summary>
        public static string Periodo {
            get {
                return ResourceManager.GetString("Periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _periodoContrato.
        /// </summary>
        public static string PeriodoContrato {
            get {
                return ResourceManager.GetString("PeriodoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _RFC.
        /// </summary>
        public static string RFC {
            get {
                return ResourceManager.GetString("RFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _salario.
        /// </summary>
        public static string Salario {
            get {
                return ResourceManager.GetString("Salario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _sexo.
        /// </summary>
        public static string Sexo {
            get {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminAreasUTP.
        /// </summary>
        public static string sp_adminAreasUTP {
            get {
                return ResourceManager.GetString("sp_adminAreasUTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminDivisionesUTP.
        /// </summary>
        public static string sp_adminDivisionesUTP {
            get {
                return ResourceManager.GetString("sp_adminDivisionesUTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminEstadosOferta.
        /// </summary>
        public static string sp_adminEstadosOferta {
            get {
                return ResourceManager.GetString("sp_adminEstadosOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminEstadosPostulacion.
        /// </summary>
        public static string sp_adminEstadosPostulacion {
            get {
                return ResourceManager.GetString("sp_adminEstadosPostulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Administrador_EstadoOferta_Actualizar.
        /// </summary>
        public static string sp_Administrador_EstadoOferta_Actualizar {
            get {
                return ResourceManager.GetString("sp_Administrador_EstadoOferta_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Administrador_Insertar.
        /// </summary>
        public static string sp_Administrador_Insertar {
            get {
                return ResourceManager.GetString("sp_Administrador_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_AreasDivision_Consultar.
        /// </summary>
        public static string sp_AreasDivision_Consultar {
            get {
                return ResourceManager.GetString("sp_AreasDivision_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_BeneficiosOferta_Consultar.
        /// </summary>
        public static string sp_BeneficiosOferta_Consultar {
            get {
                return ResourceManager.GetString("sp_BeneficiosOferta_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_BeneficiosOferta_Insertar.
        /// </summary>
        public static string sp_BeneficiosOferta_Insertar {
            get {
                return ResourceManager.GetString("sp_BeneficiosOferta_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Conocimiento_Actualizar.
        /// </summary>
        public static string sp_Conocimiento_Actualizar {
            get {
                return ResourceManager.GetString("sp_Conocimiento_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Conocimiento_Eliminar.
        /// </summary>
        public static string sp_Conocimiento_Eliminar {
            get {
                return ResourceManager.GetString("sp_Conocimiento_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Conocimiento_Insertar.
        /// </summary>
        public static string sp_Conocimiento_Insertar {
            get {
                return ResourceManager.GetString("sp_Conocimiento_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Conocimientos_Consultar.
        /// </summary>
        public static string sp_Conocimientos_Consultar {
            get {
                return ResourceManager.GetString("sp_Conocimientos_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_ConocimientosEgresado_Eliminar.
        /// </summary>
        public static string sp_ConocimientosEgresado_Eliminar {
            get {
                return ResourceManager.GetString("sp_ConocimientosEgresado_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_ConocimientosEgresado_Insertar.
        /// </summary>
        public static string sp_ConocimientosEgresado_Insertar {
            get {
                return ResourceManager.GetString("sp_ConocimientosEgresado_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_ConocimientosOferta_Consultar.
        /// </summary>
        public static string sp_ConocimientosOferta_Consultar {
            get {
                return ResourceManager.GetString("sp_ConocimientosOferta_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_ConocimientosOferta_Insertar.
        /// </summary>
        public static string sp_ConocimientosOferta_Insertar {
            get {
                return ResourceManager.GetString("sp_ConocimientosOferta_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_DatosContacto_Insertar.
        /// </summary>
        public static string sp_DatosContacto_Insertar {
            get {
                return ResourceManager.GetString("sp_DatosContacto_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_DetallesContacto_Insertar.
        /// </summary>
        public static string sp_DetallesContacto_Insertar {
            get {
                return ResourceManager.GetString("sp_DetallesContacto_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_DetallesContacto_PostulacionAceptada_Consultar.
        /// </summary>
        public static string sp_DetallesContacto_PostulacionAceptada_Consultar {
            get {
                return ResourceManager.GetString("sp_DetallesContacto_PostulacionAceptada_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_DivisionesUTP_Consultar.
        /// </summary>
        public static string sp_DivisionesUTP_Consultar {
            get {
                return ResourceManager.GetString("sp_DivisionesUTP_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Docentes_Insertar.
        /// </summary>
        public static string sp_Docentes_Insertar {
            get {
                return ResourceManager.GetString("sp_Docentes_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Docentes_Password_Actualizar.
        /// </summary>
        public static string sp_Docentes_Password_Actualizar {
            get {
                return ResourceManager.GetString("sp_Docentes_Password_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Docentes_UltimoAcceso_Actualizar.
        /// </summary>
        public static string sp_Docentes_UltimoAcceso_Actualizar {
            get {
                return ResourceManager.GetString("sp_Docentes_UltimoAcceso_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_Conocimientos_Consultar.
        /// </summary>
        public static string sp_Egresado_Conocimientos_Consultar {
            get {
                return ResourceManager.GetString("sp_Egresado_Conocimientos_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_DatosPersonales_Consultar.
        /// </summary>
        public static string sp_Egresado_DatosPersonales_Consultar {
            get {
                return ResourceManager.GetString("sp_Egresado_DatosPersonales_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_ExLa_Eliminar.
        /// </summary>
        public static string sp_Egresado_ExLa_Eliminar {
            get {
                return ResourceManager.GetString("sp_Egresado_ExLa_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_ExLa_Insertar.
        /// </summary>
        public static string sp_Egresado_ExLa_Insertar {
            get {
                return ResourceManager.GetString("sp_Egresado_ExLa_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_ExperienciasLaborales_Consultar.
        /// </summary>
        public static string sp_Egresado_ExperienciasLaborales_Consultar {
            get {
                return ResourceManager.GetString("sp_Egresado_ExperienciasLaborales_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_Habilidades_Consultar.
        /// </summary>
        public static string sp_Egresado_Habilidades_Consultar {
            get {
                return ResourceManager.GetString("sp_Egresado_Habilidades_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_Informacion_Basica_Consultar.
        /// </summary>
        public static string sp_Egresado_Informacion_Basica_Consultar {
            get {
                return ResourceManager.GetString("sp_Egresado_Informacion_Basica_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresados_Agregar.
        /// </summary>
        public static string sp_Egresados_Agregar {
            get {
                return ResourceManager.GetString("sp_Egresados_Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresados_DatosPersonales_Actualizar.
        /// </summary>
        public static string sp_Egresados_DatosPersonales_Actualizar {
            get {
                return ResourceManager.GetString("sp_Egresados_DatosPersonales_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresados_Password_Actualizar.
        /// </summary>
        public static string sp_Egresados_Password_Actualizar {
            get {
                return ResourceManager.GetString("sp_Egresados_Password_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresados_UltimoAcceso_Actualizar.
        /// </summary>
        public static string sp_Egresados_UltimoAcceso_Actualizar {
            get {
                return ResourceManager.GetString("sp_Egresados_UltimoAcceso_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Empresa_ActualizarInfo.
        /// </summary>
        public static string sp_Empresa_ActualizarInfo {
            get {
                return ResourceManager.GetString("sp_Empresa_ActualizarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Empresa_crearCuenta.
        /// </summary>
        public static string sp_Empresa_crearCuenta {
            get {
                return ResourceManager.GetString("sp_Empresa_crearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Empresa_DatosContacto_Insertar.
        /// </summary>
        public static string sp_Empresa_DatosContacto_Insertar {
            get {
                return ResourceManager.GetString("sp_Empresa_DatosContacto_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Empresa_Detalles_Consultar.
        /// </summary>
        public static string sp_Empresa_Detalles_Consultar {
            get {
                return ResourceManager.GetString("sp_Empresa_Detalles_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Empresas_Consultar.
        /// </summary>
        public static string sp_Empresas_Consultar {
            get {
                return ResourceManager.GetString("sp_Empresas_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Generos_Consultar.
        /// </summary>
        public static string sp_Generos_Consultar {
            get {
                return ResourceManager.GetString("sp_Generos_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Habilidad_Actualizar.
        /// </summary>
        public static string sp_Habilidad_Actualizar {
            get {
                return ResourceManager.GetString("sp_Habilidad_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Habilidad_Eliminar.
        /// </summary>
        public static string sp_Habilidad_Eliminar {
            get {
                return ResourceManager.GetString("sp_Habilidad_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Habilidad_Insertar.
        /// </summary>
        public static string sp_Habilidad_Insertar {
            get {
                return ResourceManager.GetString("sp_Habilidad_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Habilidades_Consultar.
        /// </summary>
        public static string sp_Habilidades_Consultar {
            get {
                return ResourceManager.GetString("sp_Habilidades_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_HabilidadesEgresado_Eliminar.
        /// </summary>
        public static string sp_HabilidadesEgresado_Eliminar {
            get {
                return ResourceManager.GetString("sp_HabilidadesEgresado_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_HabilidadesEgresado_Insertar.
        /// </summary>
        public static string sp_HabilidadesEgresado_Insertar {
            get {
                return ResourceManager.GetString("sp_HabilidadesEgresado_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_HabilidadesOferta_Consultar.
        /// </summary>
        public static string sp_HabilidadesOferta_Consultar {
            get {
                return ResourceManager.GetString("sp_HabilidadesOferta_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_HabilidadesOferta_Insertar.
        /// </summary>
        public static string sp_HabilidadesOferta_Insertar {
            get {
                return ResourceManager.GetString("sp_HabilidadesOferta_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_LoginAdmin.
        /// </summary>
        public static string sp_LoginAdmin {
            get {
                return ResourceManager.GetString("sp_LoginAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_LoginDocente.
        /// </summary>
        public static string sp_LoginDocente {
            get {
                return ResourceManager.GetString("sp_LoginDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_LoginEgresado.
        /// </summary>
        public static string sp_LoginEgresado {
            get {
                return ResourceManager.GetString("sp_LoginEgresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_LoginEmpresa.
        /// </summary>
        public static string sp_LoginEmpresa {
            get {
                return ResourceManager.GetString("sp_LoginEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_ActivasAdministrador_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_ActivasAdministrador_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_ActivasAdministrador_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_ActivasDocente_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_ActivasDocente_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_ActivasDocente_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_ActivasEgresado_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_ActivasEgresado_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_ActivasEgresado_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_ActivasEmpresa_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_ActivasEmpresa_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_ActivasEmpresa_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_Crear.
        /// </summary>
        public static string sp_OfertasTrabajo_Crear {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_Detalles_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_Detalles_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_Detalles_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_EmpresaFallo_Eliminar.
        /// </summary>
        public static string sp_OfertasTrabajo_EmpresaFallo_Eliminar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_EmpresaFallo_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_EnRevisionDocente_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_EnRevisionDocente_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_EnRevisionDocente_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_EnRevisionEgresado_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_EnRevisionEgresado_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_EnRevisionEgresado_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_EnRevisionEmpresa_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_EnRevisionEmpresa_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_EnRevisionEmpresa_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_FiltroEgresado_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_FiltroEgresado_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_FiltroEgresado_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_HistorialDocente_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_HistorialDocente_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_HistorialDocente_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_HistorialEgresado_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_HistorialEgresado_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_HistorialEgresado_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_HistorialEmpresa_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_HistorialEmpresa_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_HistorialEmpresa_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_Lista_Postulaciones.
        /// </summary>
        public static string sp_OfertasTrabajo_Lista_Postulaciones {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_Lista_Postulaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_NuevasAdministrador_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_NuevasAdministrador_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_NuevasAdministrador_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajo_PerfilEmpresa_Consultar.
        /// </summary>
        public static string sp_OfertasTrabajo_PerfilEmpresa_Consultar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajo_PerfilEmpresa_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertasTrabajoActivas_Cancelar.
        /// </summary>
        public static string sp_OfertasTrabajoActivas_Cancelar {
            get {
                return ResourceManager.GetString("sp_OfertasTrabajoActivas_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertaTrabajo_BanderaBeneficios_Actualizar.
        /// </summary>
        public static string sp_OfertaTrabajo_BanderaBeneficios_Actualizar {
            get {
                return ResourceManager.GetString("sp_OfertaTrabajo_BanderaBeneficios_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_OfertaTrabajo_DetallesContactoEmpresa_Insertar.
        /// </summary>
        public static string sp_OfertaTrabajo_DetallesContactoEmpresa_Insertar {
            get {
                return ResourceManager.GetString("sp_OfertaTrabajo_DetallesContactoEmpresa_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Postulaciones_Consultar.
        /// </summary>
        public static string sp_Postulaciones_Consultar {
            get {
                return ResourceManager.GetString("sp_Postulaciones_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Postulaciones_Egresado_Consultar.
        /// </summary>
        public static string sp_Postulaciones_Egresado_Consultar {
            get {
                return ResourceManager.GetString("sp_Postulaciones_Egresado_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Postulaciones_Estado_Actualizar.
        /// </summary>
        public static string sp_Postulaciones_Estado_Actualizar {
            get {
                return ResourceManager.GetString("sp_Postulaciones_Estado_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Postulaciones_Oferta_Consultar.
        /// </summary>
        public static string sp_Postulaciones_Oferta_Consultar {
            get {
                return ResourceManager.GetString("sp_Postulaciones_Oferta_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_PostulacionesOfertaActivaCancelada_Estado_Actualizar.
        /// </summary>
        public static string sp_PostulacionesOfertaActivaCancelada_Estado_Actualizar {
            get {
                return ResourceManager.GetString("sp_PostulacionesOfertaActivaCancelada_Estado_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_ResponsabilidadesOferta_Consultar.
        /// </summary>
        public static string sp_ResponsabilidadesOferta_Consultar {
            get {
                return ResourceManager.GetString("sp_ResponsabilidadesOferta_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_ResponsabilidadesOferta_Insertar.
        /// </summary>
        public static string sp_ResponsabilidadesOferta_Insertar {
            get {
                return ResourceManager.GetString("sp_ResponsabilidadesOferta_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_TiposUsuario_Buscar.
        /// </summary>
        public static string sp_TiposUsuario_Buscar {
            get {
                return ResourceManager.GetString("sp_TiposUsuario_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_TiposUsuario_Consultar.
        /// </summary>
        public static string sp_TiposUsuario_Consultar {
            get {
                return ResourceManager.GetString("sp_TiposUsuario_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Usuario_Insertar.
        /// </summary>
        public static string sp_Usuario_Insertar {
            get {
                return ResourceManager.GetString("sp_Usuario_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _sueldoMaxEstimado.
        /// </summary>
        public static string SueldoMaxEstimado {
            get {
                return ResourceManager.GetString("SueldoMaxEstimado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _sueldoMinEstimado.
        /// </summary>
        public static string SueldoMinEstimado {
            get {
                return ResourceManager.GetString("SueldoMinEstimado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _take.
        /// </summary>
        public static string Take {
            get {
                return ResourceManager.GetString("Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _tamano.
        /// </summary>
        public static string Tamano {
            get {
                return ResourceManager.GetString("Tamano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _telefono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _telefonoResponsable.
        /// </summary>
        public static string TelefonoResponsable {
            get {
                return ResourceManager.GetString("TelefonoResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _telefonos.
        /// </summary>
        public static string Telefonos {
            get {
                return ResourceManager.GetString("Telefonos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
