//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobList.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoredProcedureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobList.Resources.StoredProcedureResources", typeof(StoredProcedureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _descripcion.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idDivision.
        /// </summary>
        public static string idDivision {
            get {
                return ResourceManager.GetString("idDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaArea.
        /// </summary>
        public static string idNuevaArea {
            get {
                return ResourceManager.GetString("idNuevaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaDivision.
        /// </summary>
        public static string idNuevaDivision {
            get {
                return ResourceManager.GetString("idNuevaDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoAdministrador.
        /// </summary>
        public static string idNuevoAdministrador {
            get {
                return ResourceManager.GetString("idNuevoAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoEstadoOferta.
        /// </summary>
        public static string idNuevoEstadoOferta {
            get {
                return ResourceManager.GetString("idNuevoEstadoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoEstadoPostulacion.
        /// </summary>
        public static string idNuevoEstadoPostulacion {
            get {
                return ResourceManager.GetString("idNuevoEstadoPostulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoUsuario.
        /// </summary>
        public static string idNuevoUsuario {
            get {
                return ResourceManager.GetString("idNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idTipo.
        /// </summary>
        public static string idTipo {
            get {
                return ResourceManager.GetString("idTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idUsuario.
        /// </summary>
        public static string idUsuario {
            get {
                return ResourceManager.GetString("idUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _opcion.
        /// </summary>
        public static string Opcion {
            get {
                return ResourceManager.GetString("Opcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminAreasUTP.
        /// </summary>
        public static string sp_adminAreasUTP {
            get {
                return ResourceManager.GetString("sp_adminAreasUTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminDivisionesUTP.
        /// </summary>
        public static string sp_adminDivisionesUTP {
            get {
                return ResourceManager.GetString("sp_adminDivisionesUTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminEstadosOferta.
        /// </summary>
        public static string sp_adminEstadosOferta {
            get {
                return ResourceManager.GetString("sp_adminEstadosOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminEstadosPostulacion.
        /// </summary>
        public static string sp_adminEstadosPostulacion {
            get {
                return ResourceManager.GetString("sp_adminEstadosPostulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Administrador_Insertar.
        /// </summary>
        public static string sp_Administrador_Insertar {
            get {
                return ResourceManager.GetString("sp_Administrador_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Usuario_Insertar.
        /// </summary>
        public static string sp_Usuario_Insertar {
            get {
                return ResourceManager.GetString("sp_Usuario_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
