//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobList.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoredProcedureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobList.Resources.StoredProcedureResources", typeof(StoredProcedureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _cargo.
        /// </summary>
        public static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ConocimientoID.
        /// </summary>
        public static string ConocimientoID {
            get {
                return ResourceManager.GetString("ConocimientoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _correo.
        /// </summary>
        public static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _descripcionEgresado.
        /// </summary>
        public static string DescipcionEgresado {
            get {
                return ResourceManager.GetString("DescipcionEgresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _descripcion.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _edad.
        /// </summary>
        public static string Edad {
            get {
                return ResourceManager.GetString("Edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _empresa.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _mismaPassword.
        /// </summary>
        public static string EqualPassword {
            get {
                return ResourceManager.GetString("EqualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _generacion.
        /// </summary>
        public static string Generacion {
            get {
                return ResourceManager.GetString("Generacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idArea.
        /// </summary>
        public static string idArea {
            get {
                return ResourceManager.GetString("idArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idConocimiento.
        /// </summary>
        public static string idConocimiento {
            get {
                return ResourceManager.GetString("idConocimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idDivision.
        /// </summary>
        public static string idDivision {
            get {
                return ResourceManager.GetString("idDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idExperiencia.
        /// </summary>
        public static string idExperiencia {
            get {
                return ResourceManager.GetString("idExperiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idGenero.
        /// </summary>
        public static string idGenero {
            get {
                return ResourceManager.GetString("idGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idHabilidad.
        /// </summary>
        public static string idHabilidad {
            get {
                return ResourceManager.GetString("idHabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaArea.
        /// </summary>
        public static string idNuevaArea {
            get {
                return ResourceManager.GetString("idNuevaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaDivision.
        /// </summary>
        public static string idNuevaDivision {
            get {
                return ResourceManager.GetString("idNuevaDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaExperiencia.
        /// </summary>
        public static string idNuevaExperiencia {
            get {
                return ResourceManager.GetString("idNuevaExperiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevaHabilidad.
        /// </summary>
        public static string idNuevaHabilidad {
            get {
                return ResourceManager.GetString("idNuevaHabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoAdministrador.
        /// </summary>
        public static string idNuevoAdministrador {
            get {
                return ResourceManager.GetString("idNuevoAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoConocimiento.
        /// </summary>
        public static string idNuevoConocimiento {
            get {
                return ResourceManager.GetString("idNuevoConocimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoDocente.
        /// </summary>
        public static string idNuevoDocente {
            get {
                return ResourceManager.GetString("idNuevoDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoEgresado.
        /// </summary>
        public static string idNuevoEgresado {
            get {
                return ResourceManager.GetString("idNuevoEgresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoEstadoOferta.
        /// </summary>
        public static string idNuevoEstadoOferta {
            get {
                return ResourceManager.GetString("idNuevoEstadoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoEstadoPostulacion.
        /// </summary>
        public static string idNuevoEstadoPostulacion {
            get {
                return ResourceManager.GetString("idNuevoEstadoPostulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idNuevoUsuario.
        /// </summary>
        public static string idNuevoUsuario {
            get {
                return ResourceManager.GetString("idNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idTipo.
        /// </summary>
        public static string idTipo {
            get {
                return ResourceManager.GetString("idTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idUsuario.
        /// </summary>
        public static string idUsuario {
            get {
                return ResourceManager.GetString("idUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _idUsuarioEgresado.
        /// </summary>
        public static string idUsuarioEgresado {
            get {
                return ResourceManager.GetString("idUsuarioEgresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _nuevaDescripcion.
        /// </summary>
        public static string NuevaDescripcion {
            get {
                return ResourceManager.GetString("NuevaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _opcion.
        /// </summary>
        public static string Opcion {
            get {
                return ResourceManager.GetString("Opcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _periodo.
        /// </summary>
        public static string Periodo {
            get {
                return ResourceManager.GetString("Periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _salario.
        /// </summary>
        public static string Salario {
            get {
                return ResourceManager.GetString("Salario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminAreasUTP.
        /// </summary>
        public static string sp_adminAreasUTP {
            get {
                return ResourceManager.GetString("sp_adminAreasUTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminDivisionesUTP.
        /// </summary>
        public static string sp_adminDivisionesUTP {
            get {
                return ResourceManager.GetString("sp_adminDivisionesUTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminEstadosOferta.
        /// </summary>
        public static string sp_adminEstadosOferta {
            get {
                return ResourceManager.GetString("sp_adminEstadosOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_adminEstadosPostulacion.
        /// </summary>
        public static string sp_adminEstadosPostulacion {
            get {
                return ResourceManager.GetString("sp_adminEstadosPostulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Administrador_Insertar.
        /// </summary>
        public static string sp_Administrador_Insertar {
            get {
                return ResourceManager.GetString("sp_Administrador_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Conocimiento_Actualizar.
        /// </summary>
        public static string sp_Conocimiento_Actualizar {
            get {
                return ResourceManager.GetString("sp_Conocimiento_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Conocimiento_Eliminar.
        /// </summary>
        public static string sp_Conocimiento_Eliminar {
            get {
                return ResourceManager.GetString("sp_Conocimiento_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Conocimiento_Insertar.
        /// </summary>
        public static string sp_Conocimiento_Insertar {
            get {
                return ResourceManager.GetString("sp_Conocimiento_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_ConocimientosEgresado_Eliminar.
        /// </summary>
        public static string sp_ConocimientosEgresado_Eliminar {
            get {
                return ResourceManager.GetString("sp_ConocimientosEgresado_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_ConocimientosEgresado_Insertar.
        /// </summary>
        public static string sp_ConocimientosEgresado_Insertar {
            get {
                return ResourceManager.GetString("sp_ConocimientosEgresado_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Docentes_Insertar.
        /// </summary>
        public static string sp_Docentes_Insertar {
            get {
                return ResourceManager.GetString("sp_Docentes_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_Conocimientos_Consultar.
        /// </summary>
        public static string sp_Egresado_Conocimientos_Consultar {
            get {
                return ResourceManager.GetString("sp_Egresado_Conocimientos_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_DatosPersonales_Consultar.
        /// </summary>
        public static string sp_Egresado_DatosPersonales_Consultar {
            get {
                return ResourceManager.GetString("sp_Egresado_DatosPersonales_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_ExLa_Eliminar.
        /// </summary>
        public static string sp_Egresado_ExLa_Eliminar {
            get {
                return ResourceManager.GetString("sp_Egresado_ExLa_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_ExLa_Insertar.
        /// </summary>
        public static string sp_Egresado_ExLa_Insertar {
            get {
                return ResourceManager.GetString("sp_Egresado_ExLa_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_ExperienciasLaborales_Consultar.
        /// </summary>
        public static string sp_Egresado_ExperienciasLaborales_Consultar {
            get {
                return ResourceManager.GetString("sp_Egresado_ExperienciasLaborales_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresado_Habilidades_Consultar.
        /// </summary>
        public static string sp_Egresado_Habilidades_Consultar {
            get {
                return ResourceManager.GetString("sp_Egresado_Habilidades_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresados_Agregar.
        /// </summary>
        public static string sp_Egresados_Agregar {
            get {
                return ResourceManager.GetString("sp_Egresados_Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresados_DatosPersonales_Actualizar.
        /// </summary>
        public static string sp_Egresados_DatosPersonales_Actualizar {
            get {
                return ResourceManager.GetString("sp_Egresados_DatosPersonales_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Egresados_Password_Actualizar.
        /// </summary>
        public static string sp_Egresados_Password_Actualizar {
            get {
                return ResourceManager.GetString("sp_Egresados_Password_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Habilidad_Actualizar.
        /// </summary>
        public static string sp_Habilidad_Actualizar {
            get {
                return ResourceManager.GetString("sp_Habilidad_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Habilidad_Eliminar.
        /// </summary>
        public static string sp_Habilidad_Eliminar {
            get {
                return ResourceManager.GetString("sp_Habilidad_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Habilidad_Insertar.
        /// </summary>
        public static string sp_Habilidad_Insertar {
            get {
                return ResourceManager.GetString("sp_Habilidad_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_HabilidadesEgresado_Eliminar.
        /// </summary>
        public static string sp_HabilidadesEgresado_Eliminar {
            get {
                return ResourceManager.GetString("sp_HabilidadesEgresado_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_HabilidadesEgresado_Insertar.
        /// </summary>
        public static string sp_HabilidadesEgresado_Insertar {
            get {
                return ResourceManager.GetString("sp_HabilidadesEgresado_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_LoginAdmin.
        /// </summary>
        public static string sp_LoginAdmin {
            get {
                return ResourceManager.GetString("sp_LoginAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_LoginEgresado.
        /// </summary>
        public static string sp_LoginEgresado {
            get {
                return ResourceManager.GetString("sp_LoginEgresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_Usuario_Insertar.
        /// </summary>
        public static string sp_Usuario_Insertar {
            get {
                return ResourceManager.GetString("sp_Usuario_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _telefono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
