//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobList.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobList.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El máximo de carácteres es: .
        /// </summary>
        public static string descriptionMaxLength {
            get {
                return ResourceManager.GetString("descriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El minimo de carácteres es: .
        /// </summary>
        public static string descriptionMinLength {
            get {
                return ResourceManager.GetString("descriptionMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción no puede estar vacia.
        /// </summary>
        public static string descriptionNotEmpty {
            get {
                return ResourceManager.GetString("descriptionNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción es requerida.
        /// </summary>
        public static string descriptionRequired {
            get {
                return ResourceManager.GetString("descriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no puede ser la misma..
        /// </summary>
        public static string equalPassword {
            get {
                return ResourceManager.GetString("equalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar registro..
        /// </summary>
        public static string failDelete {
            get {
                return ResourceManager.GetString("failDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al insertar registro..
        /// </summary>
        public static string failInsert {
            get {
                return ResourceManager.GetString("failInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al modificar registro..
        /// </summary>
        public static string failUpdate {
            get {
                return ResourceManager.GetString("failUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre no puede superar 85 carácteres.
        /// </summary>
        public static string nameMaxLength {
            get {
                return ResourceManager.GetString("nameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre requiere 10 carácteres.
        /// </summary>
        public static string nameMinLength {
            get {
                return ResourceManager.GetString("nameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre no puede estar vacío.
        /// </summary>
        public static string nameNotEmpty {
            get {
                return ResourceManager.GetString("nameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre es requerido.
        /// </summary>
        public static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permiten espacios en blanco.
        /// </summary>
        public static string noWhiteSpace {
            get {
                return ResourceManager.GetString("noWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supera el máximo de 30 carácteres.
        /// </summary>
        public static string PassMaxLength {
            get {
                return ResourceManager.GetString("PassMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al menos 6 carácteres requeridos.
        /// </summary>
        public static string PassMinLength {
            get {
                return ResourceManager.GetString("PassMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña no puede estar vacia.
        /// </summary>
        public static string passwordNotEmpty {
            get {
                return ResourceManager.GetString("passwordNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña es requerido.
        /// </summary>
        public static string passwordRequired {
            get {
                return ResourceManager.GetString("passwordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro eliminado correctamente..
        /// </summary>
        public static string successDelete {
            get {
                return ResourceManager.GetString("successDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro insertado correctamente..
        /// </summary>
        public static string successInsert {
            get {
                return ResourceManager.GetString("successInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro actualizado correctamente..
        /// </summary>
        public static string successUpdate {
            get {
                return ResourceManager.GetString("successUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no puede superar 15 carácteres.
        /// </summary>
        public static string userMaxLength {
            get {
                return ResourceManager.GetString("userMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario requiere al menos 5 carácteres.
        /// </summary>
        public static string userMinLength {
            get {
                return ResourceManager.GetString("userMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no puede estar vacío.
        /// </summary>
        public static string userNotEmpty {
            get {
                return ResourceManager.GetString("userNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario es requerido.
        /// </summary>
        public static string userRequired {
            get {
                return ResourceManager.GetString("userRequired", resourceCulture);
            }
        }
    }
}
